version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: viewr-dark:latest
    container_name: viewr-dark
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Add healthcheck
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Uncomment this section if you need a database
  # db:
  #   image: postgres:14-alpine
  #   container_name: viewr-dark-db
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=viewr
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped
# Uncomment if using the database service
# volumes:
#   postgres_data:
