name: Docker Build and Push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Docker build
        run: |
          docker build -t viewr-dark:test .
          echo "✅ Docker build test successful"

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.event_name != 'pull_request'
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/viewr-dark:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/viewr-dark:latest

  # Deploy job can be configured based on your hosting requirements
  deploy:
    name: Deploy to production
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add deployment status
        run: |
          echo "Deployment would happen here. Set up according to your hosting provider."
          echo "New version pushed to DockerHub: ${{ secrets.DOCKERHUB_USERNAME }}/viewr-dark:latest"
